ln -s /Users/gbataille/Documents/Prog/MyConfig/dotfiles/.ackrc            /Users/gbataille/.ackrc
ln -s /Users/gbataille/Documents/Prog/MyConfig/dotfiles/.bash_profile     /Users/gbataille/.bash_profile
ln -s /Users/gbataille/Documents/Prog/MyConfig/dotfiles/.bashrc           /Users/gbataille/.bashrc
ln -s /Users/gbataille/Documents/Prog/MyConfig/dotfiles/.gitconfig        /Users/gbataille/.gitconfig
ln -s /Users/gbataille/Documents/Prog/MyConfig/dotfiles/.gitignore_global /Users/gbataille/.gitignore_global
ln -s /Users/gbataille/Documents/Prog/MyConfig/dotfiles/.hgext            /Users/gbataille/.hgext
ln -s /Users/gbataille/Documents/Prog/MyConfig/dotfiles/.hgignore_global  /Users/gbataille/.hgignore_global
ln -s /Users/gbataille/Documents/Prog/MyConfig/dotfiles/.hgrc             /Users/gbataille/.hgrc
ln -s /Users/gbataille/Documents/Prog/MyConfig/dotfiles/.irssi            /Users/gbataille/.irssi
ln -s /Users/gbataille/Documents/Prog/MyConfig/dotfiles/.oh-my-zsh        /Users/gbataille/.oh-my-zsh
ln -s /Users/gbataille/Documents/Prog/MyConfig/dotfiles/.rspec            /Users/gbataille/.rspec
ln -s /Users/gbataille/Documents/Prog/MyConfig/dotfiles/.rtorrent.rc      /Users/gbataille/.rtorrent.rc
ln -s /Users/gbataille/Documents/Prog/MyConfig/dotfiles/.ssh              /Users/gbataille/.ssh
ln -s /Users/gbataille/Documents/Prog/MyConfig/dotfiles/.stack            /Users/gbataille/.stack
ln -s /Users/gbataille/Documents/Prog/MyConfig/dotfiles/.tmux.conf        /Users/gbataille/.tmux.conf
ln -s /Users/gbataille/Documents/Prog/MyConfig/dotfiles/.tmuxinator       /Users/gbataille/.tmuxinator
ln -s /Users/gbataille/Documents/Prog/MyConfig/dotfiles/.vim              /Users/gbataille/.vim
ln -s /Users/gbataille/Documents/Prog/MyConfig/dotfiles/.vimrc            /Users/gbataille/.vimrc
ln -s /Users/gbataille/Documents/Prog/MyConfig/dotfiles/.vrapperrc        /Users/gbataille/.vrapperrc
ln -s /Users/gbataille/Documents/Prog/MyConfig/dotfiles/.xvimrc           /Users/gbataille/.xvimrc
ln -s /Users/gbataille/Documents/Prog/MyConfig/dotfiles/.zshrc            /Users/gbataille/.zshrc
