#!/bin/sh
. "$(dirname "$0")/common.sh"

if git rev-parse --verify HEAD >/dev/null 2>&1
then
  against=HEAD
else
  # Initial commit: diff against an empty tree object
  against=$(git hash-object -t tree /dev/null)
fi

# Redirect output to stderr.
exec 1>&2

for f in $(git diff --cached --name-only --diff-filter=A -z $against);
do
  if [[ "$f" =~ ".*=" ]]; then
    cat <<\EOF
Error: Attempt to commit a file with name ending with '='.
Aborting commit
EOF
    exit 1
  fi
  if [[ "$f" =~ ".*\\\\" ]]; then
    cat <<\EOF
Error: Attempt to commit a file with name ending with '\\'.
Aborting commit
EOF
    exit 1
  fi
done
